name: Build app and run tests with Maven

on:
  workflow_dispatch:
  workflow_call:

jobs:
  runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Install and configure MySQL
      - name: Install and configure MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create database vernite_test charset utf8mb4'
          mysql -h 127.0.0.1 -uroot -proot -e 'create user "vernite"@"localhost" identified by "${{ secrets.MYSQL_PASSWORD }}"'
          mysql -h 127.0.0.1 -uroot -proot -e 'grant all on *.* to "vernite"@"localhost" with grant option'

      # Install properties secrets
      - name: Install properties
        run: 'echo "$SPRING_APPLICATION_PROPERTIES" > application.properties'
        env:
          SPRING_APPLICATION_PROPERTIES: ${{ secrets.SPRING_APPLICATION_PROPERTIES }}

      # Prepare secret for signing JWT
      - name: Prepare secret
        run: |
          echo "${{ secrets.VERNITE_2022_PRIVATE_KEY_PEM }}" > key.pem
          openssl pkcs8 -topk8 -inform pem -in key.pem -out "vernite-2022.private-key.der" -outform der -nocrypt

      # Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Cache results
      - name: Cache results
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-build-${{ github.run_id }}