name: Production checks

on:
  push:
    branches: [stable]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build-app.yml

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      configuration: vernite
